// SPDX-License-Identifier: GPL-3.0-only
// Original exercise

//! The reference solution of exercise 2.51 and the edition's addition
//! 2.51a, one module and two tests.

mod ex_2_51 {
    use ch02::sec_2_2::{
        CaptureSink, Frame, Painter, Segment, Sink, Vect, beside, render_svg, rotate_90,
        segments_painter, transform_painter, wave,
    };
    use std::rc::Rc;

    /// Exercise 2.51: `below`, the first way, analogous to the book's
    /// `beside`: transform the first painter into the bottom half of
    /// the frame, the second into the top half, and paint both.
    pub fn below_direct(painter1: &Painter, painter2: &Painter) -> Painter {
        let bottom = transform_painter(
            painter1,
            Vect::new(0.0, 0.0),
            Vect::new(1.0, 0.0),
            Vect::new(0.0, 0.5),
        );
        let top = transform_painter(
            painter2,
            Vect::new(0.0, 0.5),
            Vect::new(1.0, 0.5),
            Vect::new(0.0, 1.0),
        );
        Rc::new(move |frame: &Frame, sink: &mut dyn Sink| {
            bottom(frame, sink);
            top(frame, sink);
        })
    }

    /// Exercise 2.51's `rotate270` (from the 2.50 family), needed for
    /// the second construction: a direct transform with the origin at
    /// the top left corner.
    fn rotate_270_direct(painter: &Painter) -> Painter {
        transform_painter(
            painter,
            Vect::new(0.0, 1.0),
            Vect::new(0.0, 0.0),
            Vect::new(1.0, 1.0),
        )
    }

    /// Exercise 2.51: `below`, the second way, out of `beside` and
    /// rotations: stand both painters up on their sides (270 degrees
    /// counterclockwise moves the bottom of each image to the left
    /// half), sit them side by side, then turn the whole arrangement
    /// back 90 degrees so the first painter lands in the bottom half.
    pub fn below_rotated(painter1: &Painter, painter2: &Painter) -> Painter {
        rotate_90(&beside(
            &rotate_270_direct(painter1),
            &rotate_270_direct(painter2),
        ))
    }

    /// Two asymmetric probe painters: a low stroke for the bottom slot
    /// and a high stroke for the top slot, so a swapped argument or a
    /// wrong rotation shows up as moved geometry.
    fn probes() -> (Painter, Painter) {
        let low = segments_painter(vec![Segment::new(Vect::new(0.1, 0.2), Vect::new(0.4, 0.3))]);
        let high = segments_painter(vec![Segment::new(Vect::new(0.1, 0.7), Vect::new(0.4, 0.8))]);
        (low, high)
    }

    fn render_segments(painter: &Painter) -> String {
        let mut sink = CaptureSink::new();
        painter(&Frame::unit_square(), &mut sink);
        sink.to_text()
    }

    /// Exercise 2.51: below two ways
    ///
    /// Returns the rendered segment sets of the probe pair painted by
    /// the direct `below` and by the rotation-composed `below`, which
    /// must agree.
    pub fn ex_2_51() -> (String, String) {
        let (low, high) = probes();
        (
            render_segments(&below_direct(&low, &high)),
            render_segments(&below_rotated(&low, &high)),
        )
    }

    /// The probe pair lands with the low stroke in the bottom half and
    /// the high stroke in the top half, for both constructions: the
    /// geometry check the string equality alone does not pin.
    #[test]
    fn both_belows_keep_bottom_and_top_slots() {
        let (low, high) = probes();
        for below in [below_direct(&low, &high), below_rotated(&low, &high)] {
            let mut sink = CaptureSink::new();
            below(&Frame::unit_square(), &mut sink);
            let lines = sink.lines();
            assert_eq!(lines.len(), 2);
            let (a, b) = lines[0];
            assert!(a.y < 0.5 && b.y < 0.5, "low stroke not in the bottom half");
            let (a, b) = lines[1];
            assert!(a.y > 0.5 && b.y > 0.5, "high stroke not in the top half");
        }
    }

    /// Exercise 2.51a (this edition): the below-via-rotate composition
    /// check.
    ///
    /// Exercise 2.51's string equality runs on one tiny probe pair.
    /// This addition re-proves the identity on the real `wave` painter
    /// at the SVG level, where the composition must produce
    /// byte-identical documents, and adds the argument-order check the
    /// identity does not cover for free: stacking `wave` over the X
    /// painter must put the wave in the bottom half and the X in the
    /// top half. The figure pair `below_direct.std.svg` and
    /// `below_rotate.std.svg` is generated by the picture-language
    /// example and verified against these painters byte for byte.
    ///
    /// Returns the two SVG documents for `below(wave, wave)`, direct
    /// and rotated, which must be identical.
    pub fn ex_2_51a() -> (String, String) {
        let w = wave();
        (
            render_svg(&below_direct(&w, &w), 200),
            render_svg(&below_rotated(&w, &w), 200),
        )
    }

    /// The SVG documents agree byte for byte, and the argument-order
    /// probe puts each painter in its slot.
    #[test]
    fn rotated_below_matches_direct_on_wave() {
        let (direct, rotated) = ex_2_51a();
        assert_eq!(direct, rotated);
        assert!(direct.contains("<line"));

        let w = wave();
        let x = segments_painter(vec![
            Segment::new(Vect::new(0.0, 0.0), Vect::new(1.0, 1.0)),
            Segment::new(Vect::new(0.0, 1.0), Vect::new(1.0, 0.0)),
        ]);
        let stacked = below_direct(&w, &x);
        let mut sink = CaptureSink::new();
        stacked(&Frame::unit_square(), &mut sink);
        let lines = sink.lines();
        let (wave_part, x_part) = lines.split_at(18);
        for (a, b) in wave_part {
            assert!(a.y < 0.5 && b.y < 0.5, "wave escaped the bottom half");
        }
        for (a, b) in x_part {
            assert!(a.y >= 0.5 && b.y >= 0.5, "X escaped the top half");
        }
    }

    /// The checked-in 2.51a figure pair is fresh.
    #[test]
    fn below_figures_are_fresh() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../book/figures/generated/chap2");
        let (low, high) = probes();
        for (name, painter) in [
            ("below_direct", below_direct(&low, &high)),
            ("below_rotate", below_rotated(&low, &high)),
        ] {
            let checked_in = std::fs::read_to_string(dir.join(format!("{name}.std.svg")))
                .unwrap_or_else(|_| {
                    panic!(
                        "checked-in figure {name}.std.svg is missing; run the sec_2_2_4_picture_language example"
                    )
                });
            assert_eq!(
                checked_in,
                render_svg(&painter, 200),
                "figure {name} drifted"
            );
        }
    }
}

#[test]
fn ex_2_51() {
    assert!(matches!(
        ex_2_51::ex_2_51(),
        (direct, rotated) if direct == rotated && !direct.is_empty()
    ));
}

#[test]
fn ex_2_51a() {
    assert!(matches!(
        ex_2_51::ex_2_51a(),
        (direct, rotated) if direct == rotated && !direct.is_empty()
    ));
}
