// SPDX-License-Identifier: GPL-3.0-only
// Chapter 3, exercise 3.11

package sicp.ch3.exercises

import arrow.core.Either
import sicp.runtime.PendingSolution

/**
 * Exercise 3.11: the bank account of 3.1.1 as a message-passing object.
 * Draw the environment structure generated by `acc = makeBankAccount(50L)`,
 * `acc.deposit(40L)` = 90, `acc.withdraw(60L)` = 30, and `acc2 =
 * makeBankAccount(100L)`: where the local state for `acc` is kept, how
 * the local states of the two accounts stay distinct, and which parts of
 * the structure the two accounts share. Then say which sharing a `===`
 * comparison can observe and which part is a compile-time fact no
 * experiment can see.
 */
public interface BankAccount {
    public fun withdraw(amount: Long): Either<WithdrawError, Long>

    public fun deposit(amount: Long): Long
}

public fun makeBankAccount(balance: Long): BankAccount = throw PendingSolution()
