// SPDX-License-Identifier: GPL-3.0-only
package sicp.ch5

import sicp.guest.Assignment
import sicp.guest.Binary
import sicp.guest.Block
import sicp.guest.Break
import sicp.guest.Call
import sicp.guest.CallableReference
import sicp.guest.CheckedProgram
import sicp.guest.Continue
import sicp.guest.DataClass
import sicp.guest.DataObject
import sicp.guest.Destructure
import sicp.guest.Elvis
import sicp.guest.Expression
import sicp.guest.ExpressionStatement
import sicp.guest.For
import sicp.guest.FunctionDecl
import sicp.guest.GuestType
import sicp.guest.If
import sicp.guest.Index
import sicp.guest.Is
import sicp.guest.Lambda
import sicp.guest.Literal
import sicp.guest.LiteralKind
import sicp.guest.LocalProperty
import sicp.guest.Member
import sicp.guest.Name
import sicp.guest.PlainClass
import sicp.guest.Return
import sicp.guest.Statement
import sicp.guest.StringTemplate
import sicp.guest.This
import sicp.guest.TopProperty
import sicp.guest.Unary
import sicp.guest.When
import sicp.guest.While

/** C artifact generator for checked Kotlin-subset programs (5.51–5.52).
 * Each function value carries an executable address and a heap-allocated
 * lexical environment. Environments own mutable binding cells; neither
 * escaping closures nor mutation is lowered to a copied snapshot. */
public object CBackend {
    public fun emitProgram(checked: CheckedProgram): String = CEmitter(checked).emit()
}

private class CEmitter(
    private val checked: CheckedProgram,
) {
    private var serial = 0
    private val functions = mutableListOf<Pair<String, String>>()
    private val initializers = mutableListOf<String>()
    private val objectInitializers = mutableListOf<String>()
    private val propertyInitializers = mutableListOf<String>()
    private val constructors = linkedMapOf<String, List<String>>()
    private val dataConstructors = mutableSetOf<String>()
    private val methods = mutableListOf<Triple<String, String, String>>()
    private var statements = mutableListOf<String>()

    fun emit(): String {
        for (decl in checked.syntax.declarations) {
            when (decl) {
                is DataClass -> {
                    constructors[decl.name] = decl.properties.map { it.name }
                    dataConstructors.add(decl.name)
                }

                is PlainClass -> {
                    constructors[decl.name] = decl.properties.map { it.name }
                }

                is DataObject -> {
                    constructors[decl.name] = emptyList()
                    dataConstructors.add(decl.name)
                }

                else -> {}
            }
        }
        for (decl in checked.syntax.declarations) {
            when (decl) {
                is FunctionDecl -> {
                    val code = function(decl.name, decl.parameters.map { it.name }, decl.body)
                    initializers.add("sicp_define(root, ${quoted(decl.name)}, sicp_closure($code, root));")
                }

                is PlainClass -> {
                    for (method in decl.methods) {
                        val code = function("${decl.name}_${method.name}", listOf("this") + method.parameters.map { it.name }, method.body)
                        methods.add(Triple(decl.name, method.name, code))
                    }
                }

                else -> {}
            }
        }
        for (decl in checked.syntax.declarations) {
            when (decl) {
                is TopProperty -> {
                    val (lines, value) = collect { expression(decl.initializer) }
                    propertyInitializers.addAll(lines)
                    propertyInitializers.add("sicp_define(env, ${quoted(decl.property.name)}, $value);")
                }

                is DataObject -> {
                    objectInitializers.add("sicp_define(root, ${quoted(decl.name)}, sicp_object(${quoted(decl.name)}, 0, NULL, NULL, 1));")
                }

                else -> {}
            }
        }
        val out = StringBuilder()
        out.appendLine("/* generated by sicp.ch5.CBackend: checked source, closure-converted */")
        out.appendLine("#include <stdio.h>")
        out.appendLine("#include <stdint.h>")
        out.appendLine("#include <limits.h>")
        out.appendLine("#include <math.h>")
        out.appendLine("#include <stdlib.h>")
        out.appendLine("#include <string.h>")
        out.appendLine(C_RUNTIME)
        for ((name, _) in functions) out.appendLine("static sicp_val $name(sicp_env *, int, sicp_val *);")
        for ((_, source) in functions) out.appendLine(source)
        out.appendLine("int main(void) {")
        out.appendLine("  sicp_env *root = sicp_child(NULL);")
        out.appendLine("  sicp_env *env = root;")
        for (line in initializers) out.appendLine("  $line")
        for (line in objectInitializers) out.appendLine("  $line")
        for ((owner, name, code) in methods) out.appendLine("  sicp_method(${quoted(owner)}, ${quoted(name)}, sicp_closure($code, root));")
        for (line in propertyInitializers) out.appendLine("  $line")
        out.appendLine("  sicp_call(sicp_lookup(root, \"main\"), 0, NULL);")
        out.appendLine("  return 0;")
        out.appendLine("}")
        return out.toString()
    }

    private fun function(
        name: String,
        params: List<String>,
        body: Expression,
    ): String {
        val symbol = "sicp_fn_${sanitized(name)}_${serial++}"
        val (lines, result) = collect { if (body is Block) block(body) else expression(body) }
        val source =
            buildString {
                appendLine("static sicp_val $symbol(sicp_env *captured, int argc, sicp_val *argv) {")
                appendLine("  if (argc != ${params.size}) sicp_fail(\"Arity\");")
                appendLine("  sicp_env *env = sicp_child(captured);")
                for ((index, param) in params.withIndex()) appendLine("  sicp_define(env, ${quoted(param)}, argv[$index]);")
                for (line in lines) appendLine("  $line")
                appendLine("  return $result;")
                appendLine("}")
            }
        functions.add(symbol to source)
        return symbol
    }

    private fun fresh(): String = "v${serial++}"

    private fun quoted(text: String): String =
        buildString {
            append('"')
            for (ch in text) {
                when (ch) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(ch)
                }
            }
            append('"')
        }

    private fun sanitized(name: String): String = name.map { if (it.isLetterOrDigit() || it == '_') it else '_' }.joinToString("")

    private fun decimalLiteral(text: String): String {
        val digits = text.removePrefix("-").trimStart('0').ifEmpty { "0" }
        return if (text.startsWith("-") && digits != "0") "-$digits" else digits
    }

    private fun <T> collect(body: () -> T): Pair<List<String>, T> {
        val enclosing = statements
        statements = mutableListOf()
        val value = body()
        val lines = statements.toList()
        statements = enclosing
        return lines to value
    }

    private fun line(source: String) {
        statements.add(source)
    }

    private fun hold(value: String): String {
        val name = fresh()
        line("sicp_val $name = $value;")
        return name
    }

    private fun lines(source: List<String>) {
        statements.addAll(source)
    }

    private fun scoped(source: List<String>) {
        line("{")
        for (part in source) line("  $part")
        line("}")
    }

    private fun expression(value: Expression): String =
        when (value) {
            is Literal -> {
                when (value.kind) {
                    LiteralKind.INT, LiteralKind.LONG -> {
                        val digits = decimalLiteral(value.text)
                        val long = value.kind == LiteralKind.LONG || (checked.types[value] as? GuestType.Named)?.name == "Long"
                        when {
                            long && digits == "-9223372036854775808" -> "sicp_long(LLONG_MIN)"
                            long -> "sicp_long($digits)"
                            else -> "sicp_int($digits)"
                        }
                    }

                    LiteralKind.DOUBLE -> {
                        "sicp_double(${value.text})"
                    }

                    LiteralKind.BOOLEAN -> {
                        "sicp_bool(${if (value.text == "true") 1 else 0})"
                    }

                    LiteralKind.STRING -> {
                        "sicp_str(${quoted(value.text)})"
                    }

                    LiteralKind.NULL -> {
                        "sicp_nil()"
                    }
                }
            }

            is Name -> {
                "sicp_lookup(env, ${quoted(value.text)})"
            }

            is This -> {
                "sicp_lookup(env, \"this\")"
            }

            is CallableReference -> {
                "sicp_lookup(env, ${quoted(value.name)})"
            }

            is Binary -> {
                binary(value)
            }

            is Unary -> {
                val operand = expression(value.operand)
                when (value.operator) {
                    "!" -> "sicp_bool(!sicp_truth($operand))"
                    "-" -> "sicp_neg($operand)"
                    else -> error("Unsupported C unary operator: ${value.operator}")
                }
            }

            is If -> {
                conditional(value.condition, value.yes, value.no)
            }

            is When -> {
                whenExpression(value)
            }

            is Block -> {
                if (value in checked.lambdaCoercions) {
                    "sicp_closure(${function("lambda", emptyList(), value)}, env)"
                } else {
                    block(value)
                }
            }

            is Return -> {
                returning(value)
            }

            is Lambda -> {
                "sicp_closure(${function("lambda", value.parameters.map { it.name }, value.body)}, env)"
            }

            is Call -> {
                call(value)
            }

            is Member -> {
                val receiver = hold(expression(value.receiver))
                if (value.safe) {
                    val result = fresh()
                    line("sicp_val $result = sicp_nil();")
                    line("if ($receiver.kind != S_NIL) $result = sicp_member($receiver, ${quoted(value.name)});")
                    result
                } else {
                    "sicp_member($receiver, ${quoted(value.name)})"
                }
            }

            is Index -> {
                val container = hold(expression(value.receiver))
                val index = hold(expression(value.index))
                "sicp_at($container, $index)"
            }

            is StringTemplate -> {
                var result = hold("sicp_str(\"\")")
                for (part in value.fragments) {
                    val next = hold(expression(part))
                    result = hold("sicp_concat($result, $next)")
                }
                result
            }

            is Elvis -> {
                val first = expression(value.left)
                val result = fresh()
                val (rightStatements, second) = collect { expression(value.right) }
                line("sicp_val $result = $first;")
                scoped(listOf("if ($result.kind == S_NIL) {") + rightStatements.map { "  $it" } + "  $result = $second;" + "}")
                result
            }

            is Is -> {
                val inner = expression(value.value)
                val check = "sicp_is($inner, ${quoted(typeName(value.type))})"
                if (value.negated) "sicp_bool(!$check)" else "sicp_bool($check)"
            }
        }

    private fun typeName(type: GuestType): String =
        when (type) {
            is GuestType.Named -> type.name
            is GuestType.Nullable -> typeName(type.base) + "?"
            is GuestType.Function -> "Function"
            GuestType.Nothing -> "Nothing"
            GuestType.Null -> "Null"
        }

    private fun binary(value: Binary): String {
        val left = hold(expression(value.left))
        if (value.operator == "&&" || value.operator == "||") {
            val result = fresh()
            val (rightLines, right) = collect { expression(value.right) }
            val guard = if (value.operator == "&&") result else "!$result"
            line("int $result = sicp_truth($left);")
            line("if ($guard) {")
            for (part in rightLines) line("  $part")
            line("  $result = sicp_truth($right);")
            line("}")
            return "sicp_bool($result)"
        }
        val right = hold(expression(value.right))
        val operation =
            when (value.operator) {
                "+" -> "add"
                "-" -> "sub"
                "*" -> "mul"
                "/" -> "div"
                "%" -> "mod"
                "<" -> "lt"
                ">" -> "gt"
                "<=" -> "le"
                ">=" -> "ge"
                "==" -> "eq"
                "!=" -> "ne"
                "===" -> "ident"
                "!==" -> "not_ident"
                "to" -> "pair"
                else -> error("Unsupported C binary operator: ${value.operator}")
            }
        return "sicp_$operation($left, $right)"
    }

    private fun conditional(
        condition: Expression,
        yes: Expression,
        no: Expression?,
    ): String {
        val test = expression(condition)
        val result = fresh()
        val (yesLines, yesValue) = collect { expression(yes) }
        val (noLines, noValue) = collect { no?.let { expression(it) } ?: "sicp_unit()" }
        line("sicp_val $result = sicp_unit();")
        line("if (sicp_truth($test)) {")
        for (part in yesLines) line("  $part")
        line("  $result = $yesValue;")
        line("} else {")
        for (part in noLines) line("  $part")
        line("  $result = $noValue;")
        line("}")
        return result
    }

    private fun whenExpression(value: When): String {
        val subject = value.subject?.let { hold(expression(it)) }
        val result = fresh()
        val matched = fresh()
        line("sicp_val $result = sicp_unit();")
        line("int $matched = 0;")
        for (branch in value.branches) {
            line("if (!$matched) {")
            val typePattern = branch.typePattern
            val branchPattern = branch.pattern
            val (patternLines, test) =
                collect {
                    when {
                        typePattern != null -> {
                            "sicp_is(${subject ?: "sicp_nil()"}, ${quoted(typeName(typePattern))})"
                        }

                        subject != null && branchPattern != null -> {
                            val pattern = expression(branchPattern)
                            "sicp_truth(sicp_eq($subject, $pattern))"
                        }

                        branchPattern != null -> {
                            "sicp_truth(${expression(branchPattern)})"
                        }

                        else -> {
                            "1"
                        }
                    }
                }
            for (part in patternLines) line("  $part")
            val (branchLines, branchValue) = collect { expression(branch.body) }
            line("  if ($test) {")
            for (part in branchLines) line("    $part")
            line("    $result = $branchValue;")
            line("    $matched = 1;")
            line("  }")
            line("}")
        }
        val (fallback, fallbackValue) = collect { value.otherwise?.let { expression(it) } ?: "sicp_unit()" }
        line("if (!$matched) {")
        for (part in fallback) line("  $part")
        line("  $result = $fallbackValue;")
        line("}")
        return result
    }

    private fun block(value: Block): String {
        val result = fresh()
        line("sicp_val $result = sicp_unit();")
        line("{")
        val parent = fresh()
        line("  sicp_env *$parent = env;")
        line("  sicp_env *env = sicp_child($parent);")
        val (body, last) =
            collect {
                var current = "sicp_unit()"
                for (statement in value.statements) current = statement(statement)
                current
            }
        for (part in body) line("  $part")
        line("  $result = $last;")
        line("}")
        return result
    }

    private fun returning(value: Return): String {
        val result = value.value?.let { expression(it) } ?: "sicp_unit()"
        line("return $result;")
        return result
    }

    private fun statement(value: Statement): String =
        when (value) {
            is ExpressionStatement -> {
                hold(expression(value.expression))
            }

            is LocalProperty -> {
                val init = expression(value.initializer)
                line("sicp_define(env, ${quoted(value.name)}, $init);")
                "sicp_unit()"
            }

            is FunctionDecl -> {
                val symbol = function(value.name, value.parameters.map { it.name }, value.body)
                line("sicp_define(env, ${quoted(value.name)}, sicp_closure($symbol, env));")
                "sicp_unit()"
            }

            is Assignment -> {
                val target = value.target
                val receiver =
                    when (target) {
                        is Member -> hold(expression(target.receiver))
                        is Index -> hold(expression(target.receiver))
                        else -> null
                    }
                val index = if (target is Index) hold(expression(target.index)) else null
                val previous =
                    if (value.operator == "=") {
                        null
                    } else {
                        when (target) {
                            is Name -> hold("sicp_lookup(env, ${quoted(target.text)})")
                            is Member -> hold("sicp_member($receiver, ${quoted(target.name)})")
                            is Index -> hold("sicp_at($receiver, $index)")
                            else -> error("Unsupported C assignment target")
                        }
                    }
                val rhs = hold(expression(value.value))
                val assigned =
                    if (previous == null) {
                        rhs
                    } else {
                        val op =
                            when (value.operator) {
                                "+=" -> "add"
                                "-=" -> "sub"
                                "*=" -> "mul"
                                "/=" -> "div"
                                "%=" -> "mod"
                                else -> error("Unsupported C assignment operator: ${value.operator}")
                            }
                        "sicp_$op($previous, $rhs)"
                    }
                when (target) {
                    is Name -> line("sicp_set(env, ${quoted(target.text)}, $assigned);")
                    is Member -> line("sicp_set_field($receiver, ${quoted(target.name)}, $assigned);")
                    is Index -> line("sicp_set_at($receiver, $index, $assigned);")
                    else -> error("Unsupported C assignment target")
                }
                "sicp_unit()"
            }

            is Return -> {
                returning(value)
            }

            is Break -> {
                line("break;")
                "sicp_unit()"
            }

            is Continue -> {
                line("continue;")
                "sicp_unit()"
            }

            is While -> {
                val (testLines, test) = collect { expression(value.condition) }
                val (bodyLines, _) = collect { block(value.body) }
                line("while (1) {")
                for (part in testLines) line("  $part")
                line("  if (!sicp_truth($test)) break;")
                for (part in bodyLines) line("  $part")
                line("}")
                "sicp_unit()"
            }

            is For -> {
                val sequence = hold(expression(value.iterable))
                val to = value.end?.let { hold(expression(it)) }
                val source = fresh()
                val index = fresh()
                line("sicp_val $source = ${if (to == null) sequence else "sicp_range($sequence, $to)"};")
                val (bodyLines, _) = collect { block(value.body) }
                line("for (long long $index = 0; $index < sicp_num(sicp_len($source)); $index++) {")
                val parent = fresh()
                line("  sicp_env *$parent = env;")
                line("  sicp_env *env = sicp_child($parent);")
                line("  sicp_define(env, ${quoted(value.name)}, sicp_at($source, sicp_long($index)));")
                for (part in bodyLines) line("  $part")
                line("}")
                "sicp_unit()"
            }

            is Destructure -> {
                val source = expression(value.initializer)
                val saved = fresh()
                line("sicp_val $saved = $source;")
                for ((index, name) in value.names.withIndex()) {
                    line(
                        "sicp_define(env, ${quoted(name)}, sicp_at($saved, sicp_long($index)));",
                    )
                }
                "sicp_unit()"
            }
        }

    private fun call(value: Call): String {
        val callee = value.callee
        // Evaluate each operand exactly once, from left to right, including
        // named constructor operands; property order is restored afterwards.
        if (callee is Name && callee.text in constructors) {
            val args = value.arguments.map { hold(expression(it.value)) }
            val keys = value.arguments.map { it.name ?: "" }
            val properties = constructors.getValue(callee.text)
            return "sicp_construct(${quoted(
                callee.text,
            )}, ${args.size}, (sicp_val[]){${args.ifEmpty { listOf("sicp_nil()") }.joinToString(", ")}}, " +
                "(const char *[]){${keys.ifEmpty { listOf("") }.joinToString(", ") { quoted(it) }}}, " +
                "${properties.size}, (const char *[]){${properties.ifEmpty {
                    listOf(
                        "",
                    )
                }.joinToString(", ") { quoted(it) }}}, ${if (callee.text in dataConstructors) 1 else 0})"
        }
        if (callee is Name && callee.text in setOf("print", "println")) {
            val args = value.arguments.map { hold(expression(it.value)) }
            if (args.isEmpty()) {
                if (callee.text == "println") line("putchar('\\n');")
                return "sicp_unit()"
            }
            line("sicp_print(${args[0]}, ${if (callee.text == "println") 1 else 0});")
            return "sicp_unit()"
        }
        if (callee is Name && callee.text in setOf("listOf", "mutableListOf", "setOf", "emptyList")) {
            val args = value.arguments.map { hold(expression(it.value)) }
            return "sicp_list(${args.size}, (sicp_val[]){${args.ifEmpty { listOf("sicp_nil()") }.joinToString(", ")}})"
        }
        if (callee is Name && callee.text == "Pair") {
            val args = value.arguments.map { hold(expression(it.value)) }
            return "sicp_pair(${args[0]}, ${args[1]})"
        }
        if (callee is Name && callee.text in setOf("addExact", "subtractExact", "multiplyExact", "negateExact")) {
            val args = value.arguments.map { hold(expression(it.value)) }
            val operation =
                when (callee.text) {
                    "addExact" -> "add_exact"
                    "subtractExact" -> "sub_exact"
                    "multiplyExact" -> "mul_exact"
                    else -> "neg_exact"
                }
            return "sicp_$operation(${args.joinToString(", ")})"
        }
        if (callee is Member && callee.name == "copy") {
            val type = checked.types[callee.receiver]
            val base = (type as? GuestType.Nullable)?.base ?: type
            if (base is GuestType.Named && base.name in dataConstructors) return dataCopyCall(callee, value)
        }
        if (callee is Member && callee.safe) {
            val receiver = hold(expression(callee.receiver))
            val result = fresh()
            line("sicp_val $result = sicp_nil();")
            val (branchLines, valueInBranch) =
                collect {
                    val target = hold("sicp_member($receiver, ${quoted(callee.name)})")
                    val args = value.arguments.map { hold(expression(it.value)) }
                    "sicp_call($target, ${args.size}, (sicp_val[]){${args.ifEmpty { listOf("sicp_nil()") }.joinToString(", ")}})"
                }
            line("if ($receiver.kind != S_NIL) {")
            for (part in branchLines) line("  $part")
            line("  $result = $valueInBranch;")
            line("}")
            return result
        }
        val target = hold(expression(callee))
        val args = value.arguments.map { hold(expression(it.value)) }
        return "sicp_call($target, ${args.size}, (sicp_val[]){${args.ifEmpty { listOf("sicp_nil()") }.joinToString(", ")}})"
    }

    private fun dataCopyCall(
        callee: Member,
        call: Call,
    ): String {
        val receiver = hold(expression(callee.receiver))
        val keys = call.arguments.map { it.name ?: "" }

        fun copiedValue(): String {
            val args = call.arguments.map { hold(expression(it.value)) }
            return "sicp_copy_object($receiver, ${args.size}, " +
                "(sicp_val[]){${args.ifEmpty { listOf("sicp_nil()") }.joinToString(", ")}}, " +
                "(const char *[]){${keys.ifEmpty { listOf("") }.joinToString(", ") { quoted(it) }}})"
        }
        if (!callee.safe) return copiedValue()
        val result = fresh()
        line("sicp_val $result = sicp_nil();")
        val (body, copy) = collect { copiedValue() }
        line("if ($receiver.kind != S_NIL) {")
        for (part in body) line("  $part")
        line("  $result = $copy;")
        line("}")
        return result
    }

    private companion object {
        private val C_RUNTIME =
            """
            typedef struct sicp_val sicp_val;
            typedef struct sicp_env sicp_env;
            typedef sicp_val (*sicp_code)(sicp_env *, int, sicp_val *);
            typedef enum { S_INT, S_LONG, S_DOUBLE, S_BOOL, S_STR, S_NIL, S_UNIT, S_LIST, S_PAIR, S_OBJ, S_FUN } sicp_kind;
            typedef struct sicp_cell { const char *name; sicp_val *slot; struct sicp_cell *next; } sicp_cell;
            struct sicp_env { sicp_cell *cells; sicp_env *parent; };
            typedef struct sicp_fn { sicp_code code; sicp_env *captured; sicp_val *bound; } sicp_fn;
            struct sicp_val {
                sicp_kind kind; long long integer; double decimal; int boolean; int structural; const char *text;
                sicp_val *items; const char **names; int count; const char *class_name; sicp_fn *function;
            };
            static void sicp_fail(const char *name) { fprintf(stderr, "sicp: %s\n", name); exit(1); }
            static char *sicp_copy(const char *s) {
                size_t n = strlen(s) + 1; char *p = malloc(n); memcpy(p, s, n); return p;
            }
            static sicp_val sicp_zero(sicp_kind kind) { sicp_val v = {0}; v.kind = kind; return v; }
            static sicp_val sicp_int(long long n) {
                uint32_t bits=(uint32_t)n;
                long long signed_value=bits <= 2147483647U ? bits : (long long)bits-4294967296LL;
                sicp_val v = sicp_zero(S_INT); v.integer = signed_value; return v;
            }
            static sicp_val sicp_long(long long n) { sicp_val v = sicp_zero(S_LONG); v.integer = n; return v; }
            static sicp_val sicp_double(double n) { sicp_val v = sicp_zero(S_DOUBLE); v.decimal = n; return v; }
            static sicp_val sicp_bool(int n) { sicp_val v = sicp_zero(S_BOOL); v.boolean = n != 0; return v; }
            static sicp_val sicp_str(const char *s) { sicp_val v = sicp_zero(S_STR); v.text = sicp_copy(s); return v; }
            static sicp_val sicp_nil(void) { return sicp_zero(S_NIL); }
            static sicp_val sicp_unit(void) { return sicp_zero(S_UNIT); }
            static sicp_val sicp_list(int n, const sicp_val *xs) {
                sicp_val v = sicp_zero(S_LIST); v.count = n;
                v.items = calloc((size_t)(n > 0 ? n : 1), sizeof(sicp_val));
                for (int i = 0; i < n; i++) v.items[i] = xs[i];
                return v;
            }
            static sicp_val sicp_object(const char *type, int n, const char **names, const sicp_val *xs, int structural) {
                sicp_val v = sicp_list(n, xs); v.kind = S_OBJ; v.class_name = type; v.structural = structural;
                v.names = calloc((size_t)(n > 0 ? n : 1), sizeof(char *));
                for (int i = 0; i < n; i++) v.names[i] = names[i];
                return v;
            }
            static sicp_env *sicp_child(sicp_env *parent) { sicp_env *e = calloc(1, sizeof(*e)); e->parent = parent; return e; }
            static sicp_cell *sicp_cell_of(sicp_env *e, const char *name) {
                for (; e; e = e->parent) for (sicp_cell *c = e->cells; c; c = c->next)
                    if (strcmp(c->name, name) == 0) return c;
                return NULL;
            }
            static void sicp_define(sicp_env *e, const char *name, sicp_val v) {
                sicp_cell *c = calloc(1, sizeof(*c)); c->name = name;
                c->slot = malloc(sizeof(v)); *c->slot = v; c->next = e->cells; e->cells = c;
            }
            static sicp_val sicp_lookup(sicp_env *e, const char *name) {
                sicp_cell *c = sicp_cell_of(e, name); if (!c) sicp_fail("UnassignedRead"); return *c->slot;
            }
            static sicp_val sicp_set(sicp_env *e, const char *name, sicp_val v) {
                sicp_cell *c = sicp_cell_of(e, name); if (!c) sicp_fail("UnassignedRead"); *c->slot = v; return v;
            }
            static sicp_val sicp_closure(sicp_code code, sicp_env *env) {
                sicp_val v = sicp_zero(S_FUN); v.function = calloc(1, sizeof(*v.function));
                v.function->code = code; v.function->captured = env; return v;
            }
            static sicp_val sicp_call(sicp_val fn, int n, sicp_val *args) {
                if (fn.kind != S_FUN) sicp_fail("NotCallable");
                if (!fn.function->bound) return fn.function->code(fn.function->captured, n, args);
                sicp_val *all = calloc((size_t)n + 1, sizeof(*all)); all[0] = *fn.function->bound;
                for (int i = 0; i < n; i++) all[i+1] = args[i];
                sicp_val result = fn.function->code(fn.function->captured, n+1, all); free(all); return result;
            }
            static sicp_val sicp_bound(sicp_val fn, sicp_val receiver) {
                sicp_val v = sicp_closure(fn.function->code, fn.function->captured);
                v.function->bound = malloc(sizeof(receiver)); *v.function->bound = receiver; return v;
            }
            typedef struct sicp_method_node { const char *owner, *name; sicp_val fn; struct sicp_method_node *next; } sicp_method_node;
            static sicp_method_node *sicp_methods;
            static void sicp_method(const char *owner, const char *name, sicp_val fn) {
                sicp_method_node *m = calloc(1, sizeof(*m)); m->owner=owner; m->name=name; m->fn=fn;
                m->next = sicp_methods; sicp_methods=m;
            }
            static long long sicp_num(sicp_val v) {
                if (v.kind == S_INT || v.kind == S_LONG) return v.integer;
                sicp_fail("NotInteger"); return 0;
            }
            static double sicp_decimal(sicp_val v) {
                if (v.kind == S_DOUBLE) return v.decimal;
                return (double)sicp_num(v);
            }
            static sicp_val sicp_number(sicp_kind kind, long long n) {
                return kind == S_INT ? sicp_int(n) : sicp_long(n);
            }
            static long long sicp_checked_add(long long a,long long b) {
                long long result; if (__builtin_add_overflow(a,b,&result)) sicp_fail("Overflow"); return result;
            }
            static long long sicp_checked_sub(long long a,long long b) {
                long long result; if (__builtin_sub_overflow(a,b,&result)) sicp_fail("Overflow"); return result;
            }
            static long long sicp_checked_mul(long long a,long long b) {
                long long result; if (__builtin_mul_overflow(a,b,&result)) sicp_fail("Overflow"); return result;
            }
            static long long sicp_wrap_add(long long a,long long b) {
                long long result; (void)__builtin_add_overflow(a,b,&result); return result;
            }
            static long long sicp_wrap_sub(long long a,long long b) {
                long long result; (void)__builtin_sub_overflow(a,b,&result); return result;
            }
            static long long sicp_wrap_mul(long long a,long long b) {
                long long result; (void)__builtin_mul_overflow(a,b,&result); return result;
            }
            static sicp_val sicp_neg(sicp_val v) {
                if (v.kind == S_DOUBLE) return sicp_double(-v.decimal);
                return sicp_number(v.kind, sicp_wrap_sub(0,sicp_num(v)));
            }
            static int sicp_truth(sicp_val v) { if (v.kind != S_BOOL) sicp_fail("NonBooleanCondition"); return v.boolean; }
            static sicp_val sicp_add(sicp_val a, sicp_val b) {
                if (a.kind == S_STR && b.kind == S_STR) {
                    size_t n = strlen(a.text) + strlen(b.text) + 1;
                    char *joined = malloc(n); snprintf(joined,n,"%s%s",a.text,b.text); sicp_val v = sicp_str(joined); free(joined); return v;
                }
                if (a.kind == S_LIST && b.kind == S_LIST) {
                    int n=a.count+b.count;
                    sicp_val v=sicp_zero(S_LIST);
                    v.count=n; v.items=calloc((size_t)(n>0?n:1),sizeof(sicp_val));
                    if (a.count) memcpy(v.items,a.items,(size_t)a.count*sizeof(sicp_val));
                    if (b.count) memcpy(v.items+a.count,b.items,(size_t)b.count*sizeof(sicp_val));
                    return v;
                }
                if (a.kind == S_DOUBLE) return sicp_double(sicp_decimal(a)+sicp_decimal(b));
                return sicp_number(a.kind, sicp_wrap_add(sicp_num(a),sicp_num(b)));
            }
            static sicp_val sicp_sub(sicp_val a,sicp_val b) {
                if (a.kind == S_DOUBLE) return sicp_double(sicp_decimal(a)-sicp_decimal(b));
                return sicp_number(a.kind, sicp_wrap_sub(sicp_num(a),sicp_num(b)));
            }
            static sicp_val sicp_mul(sicp_val a,sicp_val b) {
                if (a.kind == S_DOUBLE) return sicp_double(sicp_decimal(a)*sicp_decimal(b));
                return sicp_number(a.kind, sicp_wrap_mul(sicp_num(a),sicp_num(b)));
            }
            static sicp_val sicp_div(sicp_val a,sicp_val b) {
                if (a.kind == S_DOUBLE) return sicp_double(sicp_decimal(a)/sicp_decimal(b));
                if (!sicp_num(b)) sicp_fail("DivisionByZero");
                if (sicp_num(a)==LLONG_MIN && sicp_num(b)==-1) return sicp_long(LLONG_MIN);
                return sicp_number(a.kind, sicp_num(a)/sicp_num(b));
            }
            static sicp_val sicp_mod(sicp_val a,sicp_val b) {
                if (!sicp_num(b)) sicp_fail("DivisionByZero");
                if (sicp_num(a)==LLONG_MIN && sicp_num(b)==-1) return sicp_number(a.kind,0);
                return sicp_number(a.kind, sicp_num(a)%sicp_num(b));
            }
            static sicp_val sicp_exact_result(sicp_kind kind,long long value) {
                if (kind==S_INT && (value < -2147483648LL || value > 2147483647LL)) sicp_fail("Overflow");
                return sicp_number(kind,value);
            }
            static sicp_val sicp_add_exact(sicp_val a,sicp_val b) {
                return sicp_exact_result(a.kind,sicp_checked_add(sicp_num(a),sicp_num(b)));
            }
            static sicp_val sicp_sub_exact(sicp_val a,sicp_val b) {
                return sicp_exact_result(a.kind,sicp_checked_sub(sicp_num(a),sicp_num(b)));
            }
            static sicp_val sicp_mul_exact(sicp_val a,sicp_val b) {
                return sicp_exact_result(a.kind,sicp_checked_mul(sicp_num(a),sicp_num(b)));
            }
            static sicp_val sicp_neg_exact(sicp_val a) {
                return sicp_exact_result(a.kind,sicp_checked_sub(0,sicp_num(a)));
            }
            static sicp_val sicp_lt(sicp_val a,sicp_val b) {
                return sicp_bool(a.kind==S_DOUBLE ? sicp_decimal(a)<sicp_decimal(b) : sicp_num(a)<sicp_num(b));
            }
            static sicp_val sicp_le(sicp_val a,sicp_val b) {
                return sicp_bool(a.kind==S_DOUBLE ? sicp_decimal(a)<=sicp_decimal(b) : sicp_num(a)<=sicp_num(b));
            }
            static sicp_val sicp_gt(sicp_val a,sicp_val b) {
                return sicp_bool(a.kind==S_DOUBLE ? sicp_decimal(a)>sicp_decimal(b) : sicp_num(a)>sicp_num(b));
            }
            static sicp_val sicp_ge(sicp_val a,sicp_val b) {
                return sicp_bool(a.kind==S_DOUBLE ? sicp_decimal(a)>=sicp_decimal(b) : sicp_num(a)>=sicp_num(b));
            }
            static int sicp_equal(sicp_val a,sicp_val b) {
                if (a.kind != b.kind) return 0;
                if (a.kind == S_INT || a.kind == S_LONG) return a.integer == b.integer;
                if (a.kind == S_DOUBLE) return a.decimal == b.decimal;
                if (a.kind == S_BOOL) return a.boolean == b.boolean;
                if (a.kind == S_STR) return strcmp(a.text,b.text)==0;
                if (a.kind == S_NIL || a.kind == S_UNIT) return 1;
                if (a.kind == S_OBJ && !a.structural) return a.items == b.items;
                if (a.kind == S_LIST || a.kind == S_PAIR || a.kind == S_OBJ) {
                    if (a.count != b.count || (a.kind == S_OBJ && strcmp(a.class_name,b.class_name))) return 0;
                    for (int i = 0; i < a.count; i++) if (!sicp_equal(a.items[i],b.items[i])) return 0;
                    return 1;
                }
                return a.function == b.function;
            }
            static sicp_val sicp_eq(sicp_val a,sicp_val b) { return sicp_bool(sicp_equal(a,b)); }
            static sicp_val sicp_ne(sicp_val a,sicp_val b) { return sicp_bool(!sicp_equal(a,b)); }
            static sicp_val sicp_ident(sicp_val a,sicp_val b) {
                if (a.kind != b.kind) return sicp_bool(0);
                if (a.kind == S_OBJ || a.kind == S_LIST || a.kind == S_PAIR) return sicp_bool(a.items == b.items);
                if (a.kind == S_FUN) return sicp_bool(a.function == b.function);
                return sicp_eq(a,b);
            }
            static sicp_val sicp_not_ident(sicp_val a,sicp_val b) {
                sicp_val result = sicp_ident(a,b); return sicp_bool(!result.boolean);
            }
            static sicp_val sicp_pair(sicp_val a,sicp_val b) {
                sicp_val v=sicp_list(2,(sicp_val[]){a,b}); v.kind=S_PAIR; return v;
            }
            static sicp_val sicp_len(sicp_val a) {
                if (a.kind == S_STR) return sicp_int((long long)strlen(a.text));
                if (a.kind == S_LIST || a.kind == S_OBJ) return sicp_int(a.count);
                sicp_fail("NotCollection"); return sicp_nil();
            }
            static sicp_val sicp_at(sicp_val a,sicp_val i) {
                long long k = sicp_num(i);
                if ((a.kind != S_LIST && a.kind != S_PAIR && a.kind != S_OBJ) || k < 0 || k >= a.count) sicp_fail("IndexOutOfBounds");
                return a.items[k];
            }
            static sicp_val sicp_set_at(sicp_val a,sicp_val i,sicp_val v) {
                long long k = sicp_num(i);
                if (a.kind != S_LIST || k < 0 || k >= a.count) sicp_fail("IndexOutOfBounds");
                a.items[k]=v; return v;
            }
            static sicp_val sicp_member(sicp_val a,const char *name) {
                if (a.kind == S_PAIR) {
                    if (!strcmp(name,"first")) return a.items[0];
                    if (!strcmp(name,"second")) return a.items[1];
                }
                if (!strcmp(name,"size") || !strcmp(name,"length")) return sicp_len(a);
                if (a.kind == S_OBJ) {
                    for (int i=0;i<a.count;i++) if (!strcmp(a.names[i],name)) return a.items[i];
                    for (sicp_method_node *m=sicp_methods;m;m=m->next)
                        if (!strcmp(m->owner,a.class_name) && !strcmp(m->name,name)) return sicp_bound(m->fn,a);
                }
                sicp_fail("MissingMember"); return sicp_nil();
            }
            static sicp_val sicp_set_field(sicp_val a,const char *name,sicp_val v) {
                if (a.kind != S_OBJ) sicp_fail("MissingMember");
                for (int i=0;i<a.count;i++) if (!strcmp(a.names[i],name)) { a.items[i]=v; return v; }
                sicp_fail("MissingMember"); return sicp_nil();
            }
            static sicp_val sicp_construct(const char *type,int argc,sicp_val *args,const char **keys,int n,const char **fields,int structural) {
                if (argc != n) sicp_fail("Arity");
                sicp_val *ordered = calloc((size_t)(n > 0 ? n : 1),sizeof(*ordered));
                for (int i=0;i<n;i++) {
                    int found=-1;
                    for (int j=0;j<n;j++) if (!strcmp(keys[j],fields[i])) { found=j; break; }
                    ordered[i]=args[found < 0 ? i : found];
                }
                sicp_val result=sicp_object(type,n,fields,ordered,structural); free(ordered); return result;
            }
            static sicp_val sicp_copy_object(sicp_val source,int n,sicp_val *xs,const char **keys) {
                if (source.kind!=S_OBJ || !source.structural) sicp_fail("NotDataClass");
                sicp_val copy=sicp_object(source.class_name,source.count,source.names,source.items,1);
                for (int i=0;i<n;i++) {
                    int found=0;
                    for (int j=0;j<copy.count;j++) if (!strcmp(copy.names[j],keys[i])) {
                        copy.items[j]=xs[i]; found=1; break;
                    }
                    if (!found) sicp_fail("MissingProperty");
                }
                return copy;
            }
            static sicp_val sicp_range(sicp_val a,sicp_val b) {
                long long start=sicp_num(a),end=sicp_num(b),n=end>=start?end-start+1:0;
                sicp_val *items=calloc((size_t)(n>0?n:1),sizeof(*items));
                for (long long i=0;i<n;i++) items[i]=sicp_number(a.kind,start+i);
                sicp_val v=sicp_list((int)n,items); free(items); return v;
            }
            static int sicp_is(sicp_val a,const char *name) {
                char base[128];
                const char *nullable=strchr(name,'?');
                if (nullable) {
                    if (a.kind==S_NIL) return 1;
                    size_t n=(size_t)(nullable-name);
                    if (n>=sizeof(base)) sicp_fail("TypeName");
                    memcpy(base,name,n); base[n]='\0'; name=base;
                }
                if (!strcmp(name,"Int")) return a.kind==S_INT;
                if (!strcmp(name,"Long")) return a.kind==S_LONG;
                if (!strcmp(name,"Boolean")) return a.kind==S_BOOL;
                if (!strcmp(name,"Double")) return a.kind==S_DOUBLE;
                if (!strcmp(name,"String")) return a.kind==S_STR;
                if (!strcmp(name,"List")) return a.kind==S_LIST;
                if (!strcmp(name,"Pair")) return a.kind==S_PAIR;
                if (!strcmp(name,"Function")) return a.kind==S_FUN;
                if (!strcmp(name,"Null")) return a.kind==S_NIL;
                if (!strcmp(name,"Unit")) return a.kind==S_UNIT;
                return a.kind==S_OBJ && !strcmp(a.class_name,name);
            }
            static const char *sicp_show(sicp_val v) {
                char buffer[64];
                if (v.kind==S_STR) return v.text;
                if (v.kind==S_INT || v.kind==S_LONG) { snprintf(buffer,sizeof(buffer),"%lld",v.integer); return sicp_copy(buffer); }
                if (v.kind==S_DOUBLE) {
                    if (isnan(v.decimal)) return "NaN";
                    if (isinf(v.decimal)) return signbit(v.decimal) ? "-Infinity" : "Infinity";
                    if (v.decimal > -10000000.0 && v.decimal < 10000000.0 &&
                        (double)(long long)v.decimal == v.decimal) {
                        snprintf(buffer,sizeof(buffer),"%.1f",v.decimal);
                        return sicp_copy(buffer);
                    }
                    double magnitude=fabs(v.decimal);
                    int scientific=magnitude >= 10000000.0 || (magnitude > 0.0 && magnitude < 0.001);
                    for (int precision=2;precision<=17;precision++) {
                        if (scientific) snprintf(buffer,sizeof(buffer),"%.*e",precision-1,v.decimal);
                        else snprintf(buffer,sizeof(buffer),"%.*g",precision,v.decimal);
                        if (strtod(buffer,NULL)==v.decimal) break;
                    }
                    char *exponent=strchr(buffer,'e');
                    if (exponent) {
                        int power=atoi(exponent+1);
                        *exponent='\0';
                        if (!strchr(buffer,'.')) strcat(buffer,".0");
                        char printed[64];
                        snprintf(printed,sizeof(printed),"%sE%d",buffer,power);
                        return sicp_copy(printed);
                    }
                    if (!strchr(buffer,'.')) strcat(buffer,".0");
                    return sicp_copy(buffer);
                }
                if (v.kind==S_BOOL) return v.boolean ? "true" : "false";
                sicp_fail("UnassignedRead"); return "";
            }
            static sicp_val sicp_concat(sicp_val a,sicp_val b) {
                const char *left=sicp_show(a),*right=sicp_show(b);
                size_t n=strlen(left)+strlen(right)+1; char *out=malloc(n);
                snprintf(out,n,"%s%s",left,right);
                if (a.kind==S_INT || a.kind==S_LONG || a.kind==S_DOUBLE) free((void*)left);
                if (b.kind==S_INT || b.kind==S_LONG || b.kind==S_DOUBLE) free((void*)right);
                sicp_val v=sicp_zero(S_STR); v.text=out; return v;
            }
            static void sicp_print(sicp_val v,int newline) {
                const char *text=sicp_show(v);
                fputs(text,stdout); if (newline) putchar('\n');
                if (v.kind==S_INT || v.kind==S_LONG || v.kind==S_DOUBLE) free((void*)text);
            }
            """.trimIndent()
    }
}
