// SPDX-License-Identifier: GPL-3.0-only
// Chapter 1, exercise 1.14

package sicp.ch1.exercises

import sicp.runtime.PendingSolution

/**
 * Exercise 1.14: draw the tree illustrating the process generated by the
 * `countChange` procedure of section 1.2.2 in making change for 11 cents.
 * What are the orders of growth of the space and number of steps used by
 * this process as the amount to be changed increases? The growth
 * discussion is carried in the rationale; the statement lives in the
 * section 1.2 chapter text.
 *
 * The scaffold counts the tree's nodes: every call the recursive
 * change-counting procedure makes while computing change for 11 cents
 * over five kinds of coins.
 */
public fun ex_1_14(): Long = throw PendingSolution()
