(executable
 (name test_sec_2_1)
 (modules test_sec_2_1)
 (libraries sicp_ch2_solutions alcotest))

(rule
 (alias runtest)
 (action
  (run ./test_sec_2_1.exe)))

(executable
 (name prop_sec_2_12)
 (modules prop_sec_2_12)
 (libraries sicp_ch2_solutions qcheck-core qcheck-core.runner))

(rule
 (alias runtest)
 (action
  (run ./prop_sec_2_12.exe)))

(executable
 (name test_sec_2_2)
 (modules test_sec_2_2)
 (libraries sicp_ch2_solutions alcotest))

(rule
 (alias runtest)
 (deps golden_ex_2_52a.svg)
 (action
  (run ./test_sec_2_2.exe)))

(executable
 (name prop_sec_2_33)
 (modules prop_sec_2_33)
 (libraries sicp_ch2_solutions qcheck-core qcheck-core.runner))

(rule
 (alias runtest)
 (action
  (run ./prop_sec_2_33.exe)))

(executable
 (name test_sec_2_3)
 (modules test_sec_2_3)
 (libraries sicp_ch2_solutions alcotest))

(rule
 (alias runtest)
 (action
  (run ./test_sec_2_3.exe)))

(executable
 (name prop_sec_2_70)
 (modules prop_sec_2_70)
 (libraries sicp_ch2_solutions qcheck-core qcheck-core.runner))

(rule
 (alias runtest)
 (action
  (run ./prop_sec_2_70.exe)))

(executable
 (name test_sec_2_4)
 (modules test_sec_2_4)
 (libraries sicp_ch2_solutions alcotest))

(rule
 (alias runtest)
 (action
  (run ./test_sec_2_4.exe)))
