(define (square x) (* x x))
(define (even? n) (= (remainder n 2) 0))
(define (fast-expt b n)
  (cond ((= n 0) 1)
        ((even? n) (square (fast-expt b (quotient n 2))))
        (else (* b (fast-expt b (- n 1))))))
(fast-expt 2 10)
(fast-expt 3 5)
