(define (a-plus-abs-b a b)
  (if (> b 0) (+ a b) (- a b)))
(a-plus-abs-b 3 -4)
(define (sign x)
  (cond ((> x 0) 'positive)
        ((< x 0) 'negative)
        (else 'zero)))
(sign 7)
(sign -7)
(sign 0)
