(define (make-accumulator total)
  (lambda (amount)
    (set! total (+ total amount))
    total))
(define acc (make-accumulator 100))
(acc 10)
(acc 10)
(define (make-withdraw balance)
  (lambda (amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount)) balance)
        'insufficient-funds)))
(define w (make-withdraw 100))
(w 40)
(w 40)
(w 40)
