(library
 (name sicp_ch5)
 (libraries sicp_common sicp_ch4)
 (modules metacircular sec_5_1 sec_5_2 sec_5_3 sec_5_4 sec_5_5))

(executable
 (name run_sec_5_1)
 (modules run_sec_5_1)
 (libraries sicp_ch5 sicp_ch1 sicp_common))

(rule
 (alias runtest)
 (action
  (run ./run_sec_5_1.exe)))

(executable
 (name run_sec_5_2)
 (modules run_sec_5_2)
 (libraries sicp_ch5 sicp_ch1 sicp_common))

(rule
 (alias runtest)
 (action
  (run ./run_sec_5_2.exe)))

(executable
 (name run_sec_5_3)
 (modules run_sec_5_3)
 (libraries sicp_ch5 sicp_ch1 sicp_common))

(rule
 (alias runtest)
 (action
  (run ./run_sec_5_3.exe)))

(executable
 (name run_sec_5_4)
 (modules run_sec_5_4)
 (libraries sicp_ch5 sicp_ch1 sicp_common))

(rule
 (alias runtest)
 (action
  (run ./run_sec_5_4.exe)))

(executable
 (name run_sec_5_5)
 (modules run_sec_5_5)
 (libraries sicp_ch5 sicp_ch1 sicp_common))

(rule
 (alias runtest)
 (action
  (run ./run_sec_5_5.exe)))
