[package]
name = "ch04"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
autoexamples = false
autotests = false

[lib]
path = "src/lib.rs"

[[test]]
name = "corpus_core"
path = "tests/corpus_core.rs"
[[test]]
name = "scaffold_sec_4_1"
path = "../../exercises/ch04/sec_4_1.rs"

[[test]]
name = "scaffold_sec_4_2"
path = "../../exercises/ch04/sec_4_2.rs"

[[test]]
name = "scaffold_sec_4_3"
path = "../../exercises/ch04/sec_4_3.rs"

[[test]]
name = "scaffold_sec_4_4"
path = "../../exercises/ch04/sec_4_4.rs"

[[test]]
name = "solution_sec_4_1"
path = "../../solutions/ch04/sec_4_1.rs"

[[test]]
name = "solution_sec_4_2"
path = "../../solutions/ch04/sec_4_2.rs"

[[test]]
name = "solution_sec_4_3"
path = "../../solutions/ch04/sec_4_3.rs"

[[test]]
name = "solution_sec_4_4"
path = "../../solutions/ch04/sec_4_4.rs"

[[example]]
name = "sec_4_1_0_reader"
path = "examples/sec_4_1_0_reader.rs"

[[example]]
name = "sec_4_1_1_eval_apply"
path = "examples/sec_4_1_1_eval_apply.rs"

[[example]]
name = "sec_4_1_2_expressions"
path = "examples/sec_4_1_2_expressions.rs"

[[example]]
name = "sec_4_1_3_frames"
path = "examples/sec_4_1_3_frames.rs"

[[example]]
name = "sec_4_1_4_driver"
path = "examples/sec_4_1_4_driver.rs"

[[example]]
name = "sec_4_1_5_data_as_programs"
path = "examples/sec_4_1_5_data_as_programs.rs"

[[example]]
name = "sec_4_1_6_internal_definitions"
path = "examples/sec_4_1_6_internal_definitions.rs"

[[example]]
name = "sec_4_1_7_analyze"
path = "examples/sec_4_1_7_analyze.rs"


[[test]]
name = "scaffold_sec_4_5"
path = "../../exercises/ch04/sec_4_5.rs"

[[test]]
name = "solution_sec_4_5"
path = "../../solutions/ch04/sec_4_5.rs"

[[test]]
name = "scaffold_sec_4_6"
path = "../../exercises/ch04/sec_4_6.rs"

[[test]]
name = "solution_sec_4_6"
path = "../../solutions/ch04/sec_4_6.rs"

[[test]]
name = "scaffold_sec_4_7"
path = "../../exercises/ch04/sec_4_7.rs"

[[test]]
name = "solution_sec_4_7"
path = "../../solutions/ch04/sec_4_7.rs"

[[test]]
name = "scaffold_sec_4_8"
path = "../../exercises/ch04/sec_4_8.rs"

[[test]]
name = "solution_sec_4_8"
path = "../../solutions/ch04/sec_4_8.rs"

[[test]]
name = "scaffold_sec_4_9"
path = "../../exercises/ch04/sec_4_9.rs"

[[test]]
name = "solution_sec_4_9"
path = "../../solutions/ch04/sec_4_9.rs"

[[test]]
name = "scaffold_sec_4_10"
path = "../../exercises/ch04/sec_4_10.rs"

[[test]]
name = "solution_sec_4_10"
path = "../../solutions/ch04/sec_4_10.rs"

[[test]]
name = "scaffold_sec_4_11"
path = "../../exercises/ch04/sec_4_11.rs"

[[test]]
name = "solution_sec_4_11"
path = "../../solutions/ch04/sec_4_11.rs"

[[test]]
name = "scaffold_sec_4_12"
path = "../../exercises/ch04/sec_4_12.rs"

[[test]]
name = "solution_sec_4_12"
path = "../../solutions/ch04/sec_4_12.rs"

[[test]]
name = "scaffold_sec_4_13"
path = "../../exercises/ch04/sec_4_13.rs"

[[test]]
name = "solution_sec_4_13"
path = "../../solutions/ch04/sec_4_13.rs"

[[test]]
name = "scaffold_sec_4_14"
path = "../../exercises/ch04/sec_4_14.rs"

[[test]]
name = "solution_sec_4_14"
path = "../../solutions/ch04/sec_4_14.rs"

[[test]]
name = "scaffold_sec_4_15"
path = "../../exercises/ch04/sec_4_15.rs"

[[test]]
name = "solution_sec_4_15"
path = "../../solutions/ch04/sec_4_15.rs"

[[test]]
name = "scaffold_sec_4_16"
path = "../../exercises/ch04/sec_4_16.rs"

[[test]]
name = "solution_sec_4_16"
path = "../../solutions/ch04/sec_4_16.rs"

[[test]]
name = "scaffold_sec_4_17"
path = "../../exercises/ch04/sec_4_17.rs"

[[test]]
name = "solution_sec_4_17"
path = "../../solutions/ch04/sec_4_17.rs"

[[test]]
name = "scaffold_sec_4_18"
path = "../../exercises/ch04/sec_4_18.rs"

[[test]]
name = "solution_sec_4_18"
path = "../../solutions/ch04/sec_4_18.rs"

[[test]]
name = "scaffold_sec_4_19"
path = "../../exercises/ch04/sec_4_19.rs"

[[test]]
name = "solution_sec_4_19"
path = "../../solutions/ch04/sec_4_19.rs"

[[test]]
name = "scaffold_sec_4_20"
path = "../../exercises/ch04/sec_4_20.rs"

[[test]]
name = "solution_sec_4_20"
path = "../../solutions/ch04/sec_4_20.rs"

[[test]]
name = "scaffold_sec_4_21"
path = "../../exercises/ch04/sec_4_21.rs"

[[test]]
name = "solution_sec_4_21"
path = "../../solutions/ch04/sec_4_21.rs"

[[test]]
name = "scaffold_sec_4_22"
path = "../../exercises/ch04/sec_4_22.rs"

[[test]]
name = "solution_sec_4_22"
path = "../../solutions/ch04/sec_4_22.rs"

[[test]]
name = "scaffold_sec_4_23"
path = "../../exercises/ch04/sec_4_23.rs"

[[test]]
name = "solution_sec_4_23"
path = "../../solutions/ch04/sec_4_23.rs"

[[test]]
name = "scaffold_sec_4_24"
path = "../../exercises/ch04/sec_4_24.rs"

[[test]]
name = "solution_sec_4_24"
path = "../../solutions/ch04/sec_4_24.rs"

[[test]]
name = "scaffold_sec_4_25"
path = "../../exercises/ch04/sec_4_25.rs"

[[test]]
name = "solution_sec_4_25"
path = "../../solutions/ch04/sec_4_25.rs"

[[test]]
name = "scaffold_sec_4_26"
path = "../../exercises/ch04/sec_4_26.rs"

[[test]]
name = "solution_sec_4_26"
path = "../../solutions/ch04/sec_4_26.rs"

[[test]]
name = "scaffold_sec_4_27"
path = "../../exercises/ch04/sec_4_27.rs"

[[test]]
name = "solution_sec_4_27"
path = "../../solutions/ch04/sec_4_27.rs"

[[test]]
name = "scaffold_sec_4_28"
path = "../../exercises/ch04/sec_4_28.rs"

[[test]]
name = "solution_sec_4_28"
path = "../../solutions/ch04/sec_4_28.rs"

[[test]]
name = "scaffold_sec_4_29"
path = "../../exercises/ch04/sec_4_29.rs"

[[test]]
name = "solution_sec_4_29"
path = "../../solutions/ch04/sec_4_29.rs"

[[test]]
name = "scaffold_sec_4_30"
path = "../../exercises/ch04/sec_4_30.rs"

[[test]]
name = "solution_sec_4_30"
path = "../../solutions/ch04/sec_4_30.rs"

[[test]]
name = "scaffold_sec_4_31"
path = "../../exercises/ch04/sec_4_31.rs"

[[test]]
name = "solution_sec_4_31"
path = "../../solutions/ch04/sec_4_31.rs"

[[test]]
name = "scaffold_sec_4_32"
path = "../../exercises/ch04/sec_4_32.rs"

[[test]]
name = "solution_sec_4_32"
path = "../../solutions/ch04/sec_4_32.rs"

[[test]]
name = "scaffold_sec_4_33"
path = "../../exercises/ch04/sec_4_33.rs"

[[test]]
name = "solution_sec_4_33"
path = "../../solutions/ch04/sec_4_33.rs"

[[test]]
name = "scaffold_sec_4_34"
path = "../../exercises/ch04/sec_4_34.rs"

[[test]]
name = "solution_sec_4_34"
path = "../../solutions/ch04/sec_4_34.rs"

[[example]]
name = "sec_4_2_1_lazy_apply"
path = "examples/sec_4_2_1_lazy_apply.rs"

[[example]]
name = "sec_4_2_2_driver"
path = "examples/sec_4_2_2_driver.rs"

[[example]]
name = "sec_4_2_3_thunks"
path = "examples/sec_4_2_3_thunks.rs"

[dependencies]
sicp-runtime = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
proptest = { workspace = true }
insta = { workspace = true }

[lints]
workspace = true

[[example]]
name = "sec_4_3_1_search"
path = "examples/sec_4_3_1_search.rs"

[[example]]
name = "sec_4_3_2_programs"
path = "examples/sec_4_3_2_programs.rs"

[[example]]
name = "sec_4_3_3_amb_eval"
path = "examples/sec_4_3_3_amb_eval.rs"

[[test]]
name = "scaffold_sec_4_35"
path = "../../exercises/ch04/sec_4_35.rs"

[[test]]
name = "solution_sec_4_35"
path = "../../solutions/ch04/sec_4_35.rs"

[[test]]
name = "scaffold_sec_4_36"
path = "../../exercises/ch04/sec_4_36.rs"

[[test]]
name = "solution_sec_4_36"
path = "../../solutions/ch04/sec_4_36.rs"

[[test]]
name = "scaffold_sec_4_37"
path = "../../exercises/ch04/sec_4_37.rs"

[[test]]
name = "solution_sec_4_37"
path = "../../solutions/ch04/sec_4_37.rs"

[[test]]
name = "scaffold_sec_4_38"
path = "../../exercises/ch04/sec_4_38.rs"

[[test]]
name = "solution_sec_4_38"
path = "../../solutions/ch04/sec_4_38.rs"

[[test]]
name = "scaffold_sec_4_39"
path = "../../exercises/ch04/sec_4_39.rs"

[[test]]
name = "solution_sec_4_39"
path = "../../solutions/ch04/sec_4_39.rs"

[[test]]
name = "scaffold_sec_4_40"
path = "../../exercises/ch04/sec_4_40.rs"

[[test]]
name = "solution_sec_4_40"
path = "../../solutions/ch04/sec_4_40.rs"

[[test]]
name = "scaffold_sec_4_41"
path = "../../exercises/ch04/sec_4_41.rs"

[[test]]
name = "solution_sec_4_41"
path = "../../solutions/ch04/sec_4_41.rs"

[[test]]
name = "scaffold_sec_4_42"
path = "../../exercises/ch04/sec_4_42.rs"

[[test]]
name = "solution_sec_4_42"
path = "../../solutions/ch04/sec_4_42.rs"

[[test]]
name = "scaffold_sec_4_43"
path = "../../exercises/ch04/sec_4_43.rs"

[[test]]
name = "solution_sec_4_43"
path = "../../solutions/ch04/sec_4_43.rs"

[[test]]
name = "scaffold_sec_4_44"
path = "../../exercises/ch04/sec_4_44.rs"

[[test]]
name = "solution_sec_4_44"
path = "../../solutions/ch04/sec_4_44.rs"

[[test]]
name = "scaffold_sec_4_45"
path = "../../exercises/ch04/sec_4_45.rs"

[[test]]
name = "solution_sec_4_45"
path = "../../solutions/ch04/sec_4_45.rs"

[[test]]
name = "scaffold_sec_4_46"
path = "../../exercises/ch04/sec_4_46.rs"

[[test]]
name = "solution_sec_4_46"
path = "../../solutions/ch04/sec_4_46.rs"

[[test]]
name = "scaffold_sec_4_47"
path = "../../exercises/ch04/sec_4_47.rs"

[[test]]
name = "solution_sec_4_47"
path = "../../solutions/ch04/sec_4_47.rs"

[[test]]
name = "scaffold_sec_4_48"
path = "../../exercises/ch04/sec_4_48.rs"

[[test]]
name = "solution_sec_4_48"
path = "../../solutions/ch04/sec_4_48.rs"

[[test]]
name = "scaffold_sec_4_49"
path = "../../exercises/ch04/sec_4_49.rs"

[[test]]
name = "solution_sec_4_49"
path = "../../solutions/ch04/sec_4_49.rs"

[[test]]
name = "scaffold_sec_4_50"
path = "../../exercises/ch04/sec_4_50.rs"

[[test]]
name = "solution_sec_4_50"
path = "../../solutions/ch04/sec_4_50.rs"

[[test]]
name = "scaffold_sec_4_51"
path = "../../exercises/ch04/sec_4_51.rs"

[[test]]
name = "solution_sec_4_51"
path = "../../solutions/ch04/sec_4_51.rs"

[[test]]
name = "scaffold_sec_4_52"
path = "../../exercises/ch04/sec_4_52.rs"

[[test]]
name = "solution_sec_4_52"
path = "../../solutions/ch04/sec_4_52.rs"

[[test]]
name = "scaffold_sec_4_53"
path = "../../exercises/ch04/sec_4_53.rs"

[[test]]
name = "solution_sec_4_53"
path = "../../solutions/ch04/sec_4_53.rs"

[[test]]
name = "scaffold_sec_4_54"
path = "../../exercises/ch04/sec_4_54.rs"

[[test]]
name = "solution_sec_4_54"
path = "../../solutions/ch04/sec_4_54.rs"

[[test]]
name = "scaffold_sec_4_55"
path = "../../exercises/ch04/sec_4_55.rs"

[[test]]
name = "solution_sec_4_55"
path = "../../solutions/ch04/sec_4_55.rs"

[[test]]
name = "scaffold_sec_4_56"
path = "../../exercises/ch04/sec_4_56.rs"

[[test]]
name = "solution_sec_4_56"
path = "../../solutions/ch04/sec_4_56.rs"

[[test]]
name = "scaffold_sec_4_57"
path = "../../exercises/ch04/sec_4_57.rs"

[[test]]
name = "solution_sec_4_57"
path = "../../solutions/ch04/sec_4_57.rs"

[[test]]
name = "scaffold_sec_4_58"
path = "../../exercises/ch04/sec_4_58.rs"

[[test]]
name = "solution_sec_4_58"
path = "../../solutions/ch04/sec_4_58.rs"

[[test]]
name = "scaffold_sec_4_59"
path = "../../exercises/ch04/sec_4_59.rs"

[[test]]
name = "solution_sec_4_59"
path = "../../solutions/ch04/sec_4_59.rs"

[[test]]
name = "scaffold_sec_4_60"
path = "../../exercises/ch04/sec_4_60.rs"

[[test]]
name = "solution_sec_4_60"
path = "../../solutions/ch04/sec_4_60.rs"

[[test]]
name = "scaffold_sec_4_61"
path = "../../exercises/ch04/sec_4_61.rs"

[[test]]
name = "solution_sec_4_61"
path = "../../solutions/ch04/sec_4_61.rs"

[[test]]
name = "scaffold_sec_4_62"
path = "../../exercises/ch04/sec_4_62.rs"

[[test]]
name = "solution_sec_4_62"
path = "../../solutions/ch04/sec_4_62.rs"

[[test]]
name = "scaffold_sec_4_63"
path = "../../exercises/ch04/sec_4_63.rs"

[[test]]
name = "solution_sec_4_63"
path = "../../solutions/ch04/sec_4_63.rs"

[[test]]
name = "scaffold_sec_4_64"
path = "../../exercises/ch04/sec_4_64.rs"

[[test]]
name = "solution_sec_4_64"
path = "../../solutions/ch04/sec_4_64.rs"

[[test]]
name = "scaffold_sec_4_65"
path = "../../exercises/ch04/sec_4_65.rs"

[[test]]
name = "solution_sec_4_65"
path = "../../solutions/ch04/sec_4_65.rs"

[[test]]
name = "scaffold_sec_4_66"
path = "../../exercises/ch04/sec_4_66.rs"

[[test]]
name = "solution_sec_4_66"
path = "../../solutions/ch04/sec_4_66.rs"

[[test]]
name = "scaffold_sec_4_67"
path = "../../exercises/ch04/sec_4_67.rs"

[[test]]
name = "solution_sec_4_67"
path = "../../solutions/ch04/sec_4_67.rs"

[[test]]
name = "scaffold_sec_4_68"
path = "../../exercises/ch04/sec_4_68.rs"

[[test]]
name = "solution_sec_4_68"
path = "../../solutions/ch04/sec_4_68.rs"

[[test]]
name = "scaffold_sec_4_69"
path = "../../exercises/ch04/sec_4_69.rs"

[[test]]
name = "solution_sec_4_69"
path = "../../solutions/ch04/sec_4_69.rs"

[[test]]
name = "scaffold_sec_4_70"
path = "../../exercises/ch04/sec_4_70.rs"

[[test]]
name = "solution_sec_4_70"
path = "../../solutions/ch04/sec_4_70.rs"

[[test]]
name = "scaffold_sec_4_71"
path = "../../exercises/ch04/sec_4_71.rs"

[[test]]
name = "solution_sec_4_71"
path = "../../solutions/ch04/sec_4_71.rs"

[[test]]
name = "scaffold_sec_4_72"
path = "../../exercises/ch04/sec_4_72.rs"

[[test]]
name = "solution_sec_4_72"
path = "../../solutions/ch04/sec_4_72.rs"

[[test]]
name = "scaffold_sec_4_73"
path = "../../exercises/ch04/sec_4_73.rs"

[[test]]
name = "solution_sec_4_73"
path = "../../solutions/ch04/sec_4_73.rs"

[[test]]
name = "scaffold_sec_4_74"
path = "../../exercises/ch04/sec_4_74.rs"

[[test]]
name = "solution_sec_4_74"
path = "../../solutions/ch04/sec_4_74.rs"

[[test]]
name = "scaffold_sec_4_75"
path = "../../exercises/ch04/sec_4_75.rs"

[[test]]
name = "solution_sec_4_75"
path = "../../solutions/ch04/sec_4_75.rs"

[[test]]
name = "scaffold_sec_4_76"
path = "../../exercises/ch04/sec_4_76.rs"

[[test]]
name = "solution_sec_4_76"
path = "../../solutions/ch04/sec_4_76.rs"

[[test]]
name = "scaffold_sec_4_77"
path = "../../exercises/ch04/sec_4_77.rs"

[[test]]
name = "solution_sec_4_77"
path = "../../solutions/ch04/sec_4_77.rs"

[[test]]
name = "scaffold_sec_4_78"
path = "../../exercises/ch04/sec_4_78.rs"

[[test]]
name = "solution_sec_4_78"
path = "../../solutions/ch04/sec_4_78.rs"

[[test]]
name = "scaffold_sec_4_79"
path = "../../exercises/ch04/sec_4_79.rs"

[[test]]
name = "solution_sec_4_79"
path = "../../solutions/ch04/sec_4_79.rs"

[[example]]
name = "sec_4_4_1_deductive"
path = "examples/sec_4_4_1_deductive.rs"

[[example]]
name = "sec_4_4_4_driver"
path = "examples/sec_4_4_4_driver.rs"

[[example]]
name = "sec_4_4_4_evaluator"
path = "examples/sec_4_4_4_evaluator.rs"

[[example]]
name = "sec_4_4_4_matcher"
path = "examples/sec_4_4_4_matcher.rs"

[[example]]
name = "sec_4_4_4_database_streams"
path = "examples/sec_4_4_4_database_streams.rs"

[[example]]
name = "sec_4_4_4_syntax_frames"
path = "examples/sec_4_4_4_syntax_frames.rs"
