(library
 (name sicp_ch5_solutions)
 (libraries sicp_common sicp_ch5)
 (modules
  sec_5_1
  sec_5_2
  sec_5_3
  sec_5_4
  sec_5_5
  sec_5_6
  sec_5_7
  sec_5_8
  sec_5_9
  sec_5_10
  sec_5_11
  sec_5_12
  sec_5_13
  sec_5_14
  sec_5_15
  sec_5_16
  sec_5_17
  sec_5_18
  sec_5_19
  sec_5_20
  sec_5_21
  sec_5_22
  sec_5_23
  sec_5_24
  sec_5_25
  sec_5_26
  sec_5_27
  sec_5_28
  sec_5_29
  sec_5_30))
