(executables
 (names
  prop_env
  test_ast
  test_check
  test_constructor_data
  test_env
  test_random
  test_value)
 (libraries sicp_common alcotest qcheck-core qcheck-core.runner))

(rule
 (alias runtest)
 (action
  (run ./prop_env.exe)))

(rule
 (alias runtest)
 (action
  (run ./test_check.exe)))

(rule
 (alias runtest)
 (action
  (run ./test_constructor_data.exe)))

(rule
 (alias runtest)
 (action
  (run ./test_env.exe)))

(rule
 (alias runtest)
 (action
  (run ./test_random.exe)))

(rule
 (alias runtest)
 (action
  (run ./test_value.exe)))

(rule
 (alias runtest)
 (action
  (run ./test_ast.exe)))
