;; SPDX-License-Identifier: GPL-3.0-only
;; Adapted from SICP sections 4.1 to 5.2
;;
;; Runs one corpus program and prints its output in the form printer.md fixes.
;;
;; The expected files under expected/ are generated by this runner, never typed
;; by hand: an expected file nobody executed states nothing about the editions.
;; A host Scheme's own printer does not match the spec (Guile prints
;; #<procedure f> where the spec requires #[compound-procedure f]), so every
;; value goes through print-value below.
;;
;; Usage: guile -q -s runner.scm <program.scm>

(use-modules (ice-9 pretty-print)
             (ice-9 rdelim))

(define primitive-names
  '(car cdr cons list null? pair? eq? equal? + - * / = < > <= >=
    remainder quotient abs not display newline error number? symbol?
    string? apply set-car! set-cdr!))

(define (float->string value)
  "Print a float as printer.md fixes it: shortest round trip, always a point."
  (let* ((text (number->string value))
         (has-point (string-index text #\.))
         (exponent (string-index text #\e)))
    (cond
     ;; Guile writes 1e22; the spec requires the mantissa to carry a point.
     ((and exponent (not has-point))
      (string-append (substring text 0 exponent)
                     ".0"
                     (substring text exponent)))
     (has-point text)
     (else (string-append text ".0")))))

(define (escape-string text)
  (string-fold-right
   (lambda (character accumulated)
     (string-append
      (case character
        ((#\") "\\\"")
        ((#\\) "\\\\")
        (else (string character)))
      accumulated))
   ""
   text))

(define (procedure-form value)
  (let ((name (procedure-name value)))
    (cond
     ((and name (memq name primitive-names))
      (string-append "#[primitive-procedure " (symbol->string name) "]"))
     (name (string-append "#[compound-procedure " (symbol->string name) "]"))
     (else "#[compound-procedure]"))))

(define (print-value value)
  "Return the printed form of one value."
  (cond
   ((eq? value #t) "#t")
   ((eq? value #f) "#f")
   ((null? value) "()")
   ((and (number? value) (exact? value)) (number->string value))
   ((number? value) (float->string value))
   ((symbol? value) (symbol->string value))
   ((string? value) (string-append "\"" (escape-string value) "\""))
   ((procedure? value) (procedure-form value))
   ((pair? value) (print-pair value))
   (else (object->string value))))

(define (print-pair value)
  (let loop ((rest (cdr value))
             (text (string-append "(" (print-value (car value)))))
    (cond
     ((null? rest) (string-append text ")"))
     ((pair? rest) (loop (cdr rest) (string-append text " " (print-value (car rest)))))
     (else (string-append text " . " (print-value rest) ")")))))

(define (definition? form)
  (and (pair? form) (eq? (car form) 'define)))

(define (run program-path)
  (let ((module (make-fresh-user-module))
        (port (open-input-file program-path)))
    ;; grammar.md fixes `/` as returning a float, where Guile would return an
    ;; exact rational and print 1/4 for (/ 1 4).
    (eval '(define / (let ((host /)) (lambda args (exact->inexact (apply host args)))))
          module)
    (let loop ()
      (let ((form (read port)))
        (cond
         ((eof-object? form) (close-port port))
         (else
          ;; printer.md fixes a bare `try-again` symbol as asking the
          ;; program's driver for the next value, so evaluate it as a call
          ;; to the program-defined `(try-again)` procedure. Core and lazy
          ;; programs never contain the symbol; amb programs define it over
          ;; their own driver state, which the runner never inspects.
          (let ((form (if (eq? form 'try-again) '(try-again) form)))
            (catch #t
              (lambda ()
                (let ((value (eval form module)))
                  ;; A top-level define prints nothing (printer.md).
                  (unless (or (definition? form) (unspecified? value))
                    (display (print-value value))
                    (newline))))
              (lambda (key . arguments)
                ;; The spec prints one Error line and stops the program.
                (display "Error: ")
                (display (error-line key arguments))
                (newline)
                (close-port port)
                (exit 0)))
            (loop))))))))

(define (unspecified? value)
  (eq? value (if #f #f)))

(define (error-line key arguments)
  "Render a raised error as `<message> <irritant>...`.

Guile throws `(misc-error #f <format> <parts> #f)`, so the message and its
irritants are the third element, not the format string."
  (if (and (eq? key 'misc-error)
           (= (length arguments) 4)
           (pair? (caddr arguments)))
      (let ((parts (caddr arguments)))
        (string-join
         (cons (if (string? (car parts)) (car parts) (print-value (car parts)))
               (map print-value (cdr parts)))
         " "))
      (string-join (cons (symbol->string key) (map print-value arguments)) " ")))

(let ((arguments (command-line)))
  (when (null? (cdr arguments))
    (display "usage: guile -q -s runner.scm <program.scm>\n" (current-error-port))
    (exit 2))
  (run (cadr arguments)))
