[package]
name = "ch03"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
autoexamples = false
autotests = false

[lib]
path = "src/lib.rs"

[[example]]
name = "sec_3_1_1_local_state"
path = "examples/sec_3_1_1_local_state.rs"

[[example]]
name = "sec_3_1_2_benefits"
path = "examples/sec_3_1_2_benefits.rs"

[[example]]
name = "sec_3_1_3_costs"
path = "examples/sec_3_1_3_costs.rs"

[[example]]
name = "sec_3_2_1_rules"
path = "examples/sec_3_2_1_rules.rs"

[[example]]
name = "sec_3_2_2_applying"
path = "examples/sec_3_2_2_applying.rs"

[[example]]
name = "sec_3_2_3_frames"
path = "examples/sec_3_2_3_frames.rs"

[[example]]
name = "sec_3_2_4_internal"
path = "examples/sec_3_2_4_internal.rs"

[[test]]
name = "scaffold_sec_3_1"
path = "../../exercises/ch03/sec_3_1.rs"

[[test]]
name = "scaffold_sec_3_2"
path = "../../exercises/ch03/sec_3_2.rs"

[[test]]
name = "scaffold_sec_3_3"
path = "../../exercises/ch03/sec_3_3.rs"

[[test]]
name = "scaffold_sec_3_4"
path = "../../exercises/ch03/sec_3_4.rs"

[[test]]
name = "scaffold_sec_3_5"
path = "../../exercises/ch03/sec_3_5.rs"

[[test]]
name = "scaffold_sec_3_6"
path = "../../exercises/ch03/sec_3_6.rs"

[[test]]
name = "scaffold_sec_3_7"
path = "../../exercises/ch03/sec_3_7.rs"

[[test]]
name = "scaffold_sec_3_8"
path = "../../exercises/ch03/sec_3_8.rs"

[[test]]
name = "scaffold_sec_3_9"
path = "../../exercises/ch03/sec_3_9.rs"

[[test]]
name = "scaffold_sec_3_10"
path = "../../exercises/ch03/sec_3_10.rs"

[[test]]
name = "scaffold_sec_3_11"
path = "../../exercises/ch03/sec_3_11.rs"

[[test]]
name = "solution_sec_3_1"
path = "../../solutions/ch03/sec_3_1.rs"

[[test]]
name = "solution_sec_3_2"
path = "../../solutions/ch03/sec_3_2.rs"

[[test]]
name = "solution_sec_3_3"
path = "../../solutions/ch03/sec_3_3.rs"

[[test]]
name = "solution_sec_3_4"
path = "../../solutions/ch03/sec_3_4.rs"

[[test]]
name = "solution_sec_3_5"
path = "../../solutions/ch03/sec_3_5.rs"

[[test]]
name = "solution_sec_3_6"
path = "../../solutions/ch03/sec_3_6.rs"

[[test]]
name = "solution_sec_3_7"
path = "../../solutions/ch03/sec_3_7.rs"

[[test]]
name = "solution_sec_3_8"
path = "../../solutions/ch03/sec_3_8.rs"

[[test]]
name = "solution_sec_3_9"
path = "../../solutions/ch03/sec_3_9.rs"

[[test]]
name = "solution_sec_3_10"
path = "../../solutions/ch03/sec_3_10.rs"

[[test]]
name = "solution_sec_3_11"
path = "../../solutions/ch03/sec_3_11.rs"

[dependencies]
sicp-runtime = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
proptest = { workspace = true }
insta = { workspace = true }

[lints]
workspace = true
