# SPDX-License-Identifier: MIT
"""Re-run every Scheme corpus program and compare its output to the expected file.

The expected files are generated by `spec/scheme-subset/runner.scm`, so this
check is what keeps them honest: an expected file that no longer matches the
program it came from is a defect in one of the two, never something to accept.
It also holds the manifest and the tree to the same set of programs, so a
program cannot be added without a row or listed without existing.
"""

import argparse
import os
import subprocess
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

HEADER_LINES = 2
MANIFEST_FIELDS = 5

# The settled corpus: 39 programs across six capabilities. The manifest alone
# cannot be the contract, because a manifest listing half the corpus would
# otherwise pass and read as a covered subset.
REQUIRED_PROGRAMS: dict[str, int] = {
    "core": 21,
    "lazy": 4,
    "amb": 4,
    "query": 4,
    "machine": 4,
    "compiler": 2,
}
REQUIRED_NAMES: frozenset[str] = frozenset({"core/metacircular.scm"})


@dataclass(frozen=True, slots=True)
class Row:
    """One manifest row: a program, its expected output, and how it is run."""

    capability: str
    program: str
    expected: str
    mode: str
    evaluators: str


def read_manifest(path: Path) -> list[Row]:
    """Parse the manifest, skipping its comment and licence lines."""
    rows: list[Row] = []
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        text = line.strip()
        if not text or text.startswith((";;", "#")):
            continue
        fields = line.split("\t")
        if len(fields) != MANIFEST_FIELDS:
            raise ValueError(
                f"{path}:{number}: expected {MANIFEST_FIELDS} tab-separated fields, "
                f"found {len(fields)}"
            )
        rows.append(Row(*(field.strip() for field in fields)))
    return rows


def expected_output(path: Path) -> str:
    """Return an expected file's payload, dropping its two licence header lines."""
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    return "".join(lines[HEADER_LINES:])


def run_program(guile: str, runner: Path, program: Path) -> str:
    """Run one corpus program through the spec runner."""
    result = subprocess.run(
        [guile, "-q", "--no-auto-compile", "-s", str(runner), str(program)],
        capture_output=True,
        text=True,
        check=False,
        timeout=120,
    )
    if result.returncode != 0:
        raise ValueError(f"{program}: runner exited {result.returncode}: {result.stderr.strip()}")
    return result.stdout


def check_coverage(root: Path, rows: list[Row], capability: str | None = None) -> list[str]:
    """Report manifest and tree disagreements, and any capability still short.

    `capability` narrows the inventory to one capability, so a scoped run is not
    failed by the capabilities it was asked to skip. The manifest-against-tree
    comparison stays whole, because a stray or dangling program is a defect in
    the corpus however the run was scoped.
    """
    listed = {row.program for row in rows}
    present = {
        str(path.relative_to(root / "programs")) for path in (root / "programs").rglob("*.scm")
    }
    defects = [f"{name}: on disk but not in the manifest" for name in sorted(present - listed)]
    defects.extend(f"{name}: in the manifest but not on disk" for name in sorted(listed - present))
    counted = Counter(row.capability for row in rows)
    required_programs = {
        name: count for name, count in REQUIRED_PROGRAMS.items() if capability in (None, name)
    }
    defects.extend(
        f"{name}: {counted[name]} of {count} programs present"
        for name, count in required_programs.items()
        if counted[name] != count
    )
    required_names = {
        name for name in REQUIRED_NAMES if capability in (None, name.split("/", 1)[0])
    }
    defects.extend(f"{name}: required program absent" for name in sorted(required_names - listed))
    return defects


def main(argv: list[str] | None = None) -> int:
    """Run the checks and return the process exit status."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("spec/scheme-subset"))
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--capability", help="check only this capability")
    parser.add_argument("--guile", default=os.environ.get("GUILE", "guile"))
    args = parser.parse_args(argv)

    root: Path = args.root
    manifest = args.manifest if args.manifest is not None else root / "manifest.txt"
    runner = root / "runner.scm"
    for required in (manifest, runner):
        if not required.is_file():
            print(f"scheme_corpus_check: missing {required}", file=sys.stderr)
            return 1

    try:
        rows = read_manifest(manifest)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    defects = check_coverage(root, rows, args.capability)
    selected = [row for row in rows if args.capability in (None, row.capability)]
    checked = 0
    for row in selected:
        program = root / "programs" / row.program
        expected = root / "expected" / row.expected
        if not expected.is_file():
            defects.append(f"{row.program}: expected file missing: {expected}")
            continue
        try:
            produced = run_program(args.guile, runner, program)
        except (OSError, ValueError, subprocess.SubprocessError) as exc:
            defects.append(str(exc))
            continue
        checked += 1
        if produced != expected_output(expected):
            defects.append(f"{row.program}: output differs from {row.expected}")

    for defect in defects:
        print(defect, file=sys.stderr)
    print(f"programs={checked} defects={len(defects)}")
    return 1 if defects else 0


if __name__ == "__main__":
    raise SystemExit(main())
